spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devices
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect